### ISSUE TITLE
download() ignoring filename

### ISSUE THREAD

**Issue by r-pascal** [vsmoraes/pdf-laravel5#10]
Laravel Framework version 5.2.7
Since the last "pdf-laravel5" update from 2015-01-11, the download() method ignores the filename() method and stores every pdf as "dompdf_out.pdf"

```
$html = view('invoice')->render();

// DOWNLOAD
return \PDF::load($html)
    ->filename('newFilename.pdf')
    ->download();
```

**Comment by vsmoraes** [comment]
Sorry, mea culpa. I'm creating a new branch with this fix

**Comment by vsmoraes** [comment]
Problem solved with the last update

**Comment by r-pascal** [comment]
👍
