### ISSUE TITLE
I get weird stuff when I generate pdf

### ISSUE THREAD

**Issue by yvesgeolingo** [vsmoraes/pdf-laravel5#13]
![sc1](https://cloud.githubusercontent.com/assets/8737745/13840399/52017362-ec5d-11e5-974b-260d293fcfb8.PNG)

These are my code..

View:
![sc2](https://cloud.githubusercontent.com/assets/8737745/13840430/82a49ef4-ec5d-11e5-99a5-4e7cad026950.PNG)

Controller:
![sc3](https://cloud.githubusercontent.com/assets/8737745/13840447/9107ad4c-ec5d-11e5-90fa-e6a2fc4d598d.PNG)

**Comment by yvesgeolingo** [comment]
When I @extend the default layout.blade.php it works but it displays the nav bar too. And when I decide to remove the nav bar, it shows weird stuff again. I've looked online for answers but I don't seem to find any. Thanks

**Comment by vsmoraes** [comment]
We're update the package to the last version of laravel and dompdf, please udpate your project and open a new issue if the problem still exists.

Thanks for the patience!
