### ISSUE TITLE
not support unicode 

### ISSUE THREAD

**Issue by mengheangrat** [vsmoraes/pdf-laravel5#14]
'??????'

**Comment by vsmoraes** [comment]
You just have to enable it. This component supports constants to configure DOMPDF.
As seen here: https://github.com/dompdf/dompdf/wiki/UnicodeHowTo, you just need to define  a constant `DOMPDF_UNICODE_ENABLED` as `true`.

**Comment by vsmoraes** [comment]
We're update the package to the last version of laravel and dompdf, please udpate your project and open a new issue if the problem still exists.

Thanks for the patience!
