### ISSUE TITLE
Image not found or type unknown

### ISSUE THREAD

**Issue by sk8sta13** [vsmoraes/pdf-laravel5#15]
Hi, I am using the example which is in github, but the images are not aparecendeo always get this message "Image not found or type unknown".

I'm trying to images of type png and jpg

**Comment by atiladelcanton** [comment]
I have the same problem

**Comment by vsmoraes** [comment]
Can you guys provide some real examples?

**Comment by sk8sta13** [comment]
the view is usually performed

$router->get('/pdf/view', function() {
    $html = view('pdfs.example')->render();

```
return PDF::load($html)->show();
```

});

**Comment by ghost** [comment]
@vsmoraes  Please find the below screenshot
![temp](https://cloud.githubusercontent.com/assets/11065713/17326761/04a0c77c-58d1-11e6-8bbb-8f6d365c059d.png)

**Comment by sujit223** [comment]
Hi guys,

Something like this might help
`<img src="{!! public_path().'/uploads/company'.'/'.$company->logo !!}"/>`

This helps my issue fixed.

**Comment by Grald** [comment]
thanks @sujit223

**Comment by jessepowers** [comment]
Confirmed. @sujit223 had it right, it has to be public_path().

**Comment by astaphobia** [comment]
in my case, used public_path() helpers still get error images not found,
my code `{{public_path() . '/asset/images/logo.png'}}`

**Comment by vsmoraes** [comment]
Instead of passing the view through the pdf library, try to render it directly on the browser - in pure html - and see if the images still don't show. I'm saying this because there is no magic here, if the html can render the image so can the pdf library.

**Comment by astaphobia** [comment]
The problem can fixed, encode image to base64.

**Comment by hazzo** [comment]
@astaphobia is right:

`$path = 'myfolder/myimage.png';`
`$type = pathinfo($path, PATHINFO_EXTENSION);`
`$data = file_get_contents($path);`
`$base64 = 'data:image/' . $type . ';base64,' . base64_encode($data);`

`<img src="{!! $base64 !!}" alt=""/>`

How to base64 img: http://stackoverflow.com/questions/3967515/how-to-convert-image-to-base64-encoding

**Comment by vsmoraes** [comment]
We're update the package to the last version of laravel and dompdf, please udpate your project and open a new issue if the problem still exists.

Thanks for the patience!

**Comment by aminaminamin93** [comment]
Thanks @astaphobia & @hazzo
