### ISSUE TITLE
problem with {{ url() }} / linking

### ISSUE THREAD

**Issue by techtona** [vsmoraes/pdf-laravel5#16]
long loading when access out url for images or css

**Comment by vsmoraes** [comment]
Can you provide some examples?

**Comment by joaonzangoII** [comment]
It takes long even when loading assets for example 
`<link href="{{asset('css/vendor.css')}}" rel="stylesheet"/>` or even `<script src="{{asset('js/vendor.js')}}" type="text/javascript"></script>`
