### ISSUE TITLE
Could not download large set of data

### ISSUE THREAD

**Issue by nahdonivr** [vsmoraes/pdf-laravel5#17]
When trying to download the data amount of data (more than 2000 rows), then I got site not reach error. For low amount of data it works fine. 
![capture](https://cloud.githubusercontent.com/assets/7066957/17127032/0fbf8dfc-5320-11e6-96b0-14873b6d6e6f.PNG)

**Comment by sujit223** [comment]
from where are u trying to download

**Comment by nahdonivr** [comment]
I am still having this issue. can anyone here me to fix this issue? Thanks in advance

**Comment by Hoheckell** [comment]
same error here, about 1000 rows on query to output

**Comment by vsmoraes** [comment]
We're update the package to the last version of laravel and dompdf, please udpate your project and open a new issue if the problem still exists.

Thanks for the patience!

**Comment by nahdonivr** [comment]
Thank you :)
