### ISSUE TITLE
Class 'Vsmoraes\Pdf\PdfServiceProvider' not found

### ISSUE THREAD

**Issue by shafqatjan** [vsmoraes/pdf-laravel5#18]
I have installed this package at windows local server working fine when im doing live at linux shared hosting it is showing this error

FatalErrorException in ProviderRepository.php line 146:
Class 'Vsmoraes\Pdf\PdfServiceProvider' not found

app.php
Vsmoraes\Pdf\PdfServiceProvider::class,   ///provider
'PDF' => 'Vsmoraes\Pdf\PdfFacade',    //aliases

in vendor folder vsmoraes/laravel-pdf/src/.....    ///all files

Please let me what is the issue at linux.

**Comment by vsmoraes** [comment]
We're update the package to the last version of laravel and dompdf, please udpate your project and open a new issue if the problem still exists.

Thanks for the patience!
