### ISSUE TITLE
Does not allow for multiple PDF generation in a single request.

### ISSUE THREAD

**Issue by mgwoolf** [vsmoraes/pdf-laravel5#19]
When generating multiple PDF's in a single request I get the following error message on the 2nd attempt to generate the PDF.

```
DOMPDF_Exception in inline_positioner.cls.php line 37:
No block-level parent found. Not good.
```

It appears that the PDF object is only able to create a single PDF per request.

Unfortunately the PDF object is only instantiated when the service provider is registered and theres doesn't seem to be anyway way to re-isntatantiate the DOMPDF object at runtime.  Is it possible to  provide an additional method to create a new instantiation of DOMPDF?   Could the current instance be unset and new instance created with a new method?

**Comment by vsmoraes** [comment]
We're update the package to the last version of laravel and dompdf, please udpate your project and open a new issue if the problem still exists.

Thanks for the patience!
