### ISSUE TITLE
"Not Instantiable"

### ISSUE THREAD

**Issue by richardtorres314** [vsmoraes/pdf-laravel5#2]
BindingResolutionException in Container.php line 785:
Target [Vsmoraes\Pdf\Pdf] is not instantiable.

The package was just working until I updated composer, never worked since.

**Comment by vsmoraes** [comment]
I couldn't reproduce the error yet, but I'm looking into it.

**Comment by vsmoraes** [comment]
@richardtorres314 try changing the version of the package on your `composer.json` from `dev-master` to `1.0.1`

**Comment by richardtorres314** [comment]
Worked like a charm! Thank you for such a speedy response.

I think there's a typo in your readme: did you mean BaseController as opposed to BaseControler?

Thank you!!

**Comment by vsmoraes** [comment]
Anytime! Thanks for reporting the error and the typo =)
