### ISSUE TITLE
save file before download

### ISSUE THREAD

**Issue by engsamar** [vsmoraes/pdf-laravel5#23]
how can i save file with special name and then download it

**Comment by stoneshaq** [comment]
return \PDF::load($html)->filename('whateverfilename-'.$id.'.pdf')->show(); or
return \PDF::load($html)->filename('whateverfilename-'.$id.'.pdf')->download();

**Comment by vsmoraes** [comment]
We're update the package to the last version of laravel and dompdf, please udpate your project and open a new issue if the problem still exists.

Thanks for the patience!
