### ISSUE TITLE
Constant DOMPDF_ENABLE_AUTOLOAD already defined

### ISSUE THREAD

**Issue by Aeliot-Tm** [vsmoraes/pdf-laravel5#24]
I'd like to use Vsmoraes\Pdf\Pdf in several places, but i catch an error "Constant DOMPDF_ENABLE_AUTOLOAD already defined"

As i see, code in your Vsmoraes\Pdf\PdfServiceProvider should be like this:
`defined('DOMPDF_ENABLE_AUTOLOAD') || define('DOMPDF_ENABLE_AUTOLOAD', false);`
instead of
`define('DOMPDF_ENABLE_AUTOLOAD', false);`

And i think, it will be a good idea to bind Vsmoraes\Pdf\Pdf as shared.

**Comment by vsmoraes** [comment]
We're update the package to the last version of laravel and dompdf, please udpate your project and open a new issue if the problem still exists.

Thanks for the patience!
