### ISSUE TITLE
Statically called method not working.

### ISSUE THREAD

**Issue by joshharington** [vsmoraes/pdf-laravel5#26]
I keep getting the error `Non-static method Vsmoraes\Pdf\Pdf::load() cannot be called statically` when trying to load a view html for download

**Comment by vsmoraes** [comment]
Hi there, Josh. Can you provide a sample of the code you're trying to run? I'm asking this because `Vsmoraes\Pdf\Pdf` is the main interface and not the concrete (or the facade, in your case) implementation.
