### ISSUE TITLE
Title doesn't display properly

### ISSUE THREAD

**Issue by richardtorres314** [vsmoraes/pdf-laravel5#3]
Is there anyway to have the title display the text of the title rather than the route? My title tags don't seem to be working no matter where they're placed. Thank you!

**Comment by vsmoraes** [comment]
If you mean the window title, I don't think it's possible considering that you're replacing all the HTML with the PDF. What you can do is to set the filename (`$pdf->filename('my test pdf.pdf');`) and it will appear as the tab or window title.
