### ISSUE TITLE
output() method not working

### ISSUE THREAD

**Issue by r-pascal** [vsmoraes/pdf-laravel5#7]
Laravel Framework version 5.2.6
show() and download() methods working fine, so setup shouldn't be the problem.
Trying to store the pdf on the filesystem returns no error, but the file is not stored on the filesystem.

```
$html = view('invoice', compact('invoice'))->render();

$result = \PDF::load($html)
            ->filename(storage_path('app/invoices/inv-123.pdf'))
            ->output();
```

**Comment by vsmoraes** [comment]
Bug fixed with on the new release.

**Comment by r-pascal** [comment]
thanks
