### ISSUE TITLE
print of showing data in table (including filter)

### ISSUE THREAD

**Issue by semengeyza** [vsmoraes/pdf-laravel5#8]
making a filtering table, how to get that data instead of call it manually by @foreach method ?

**Comment by vsmoraes** [comment]
What data? This problem is related to the PDF component or the Laravel View (blade) component?

**Comment by semengeyza** [comment]
on view component. i don't know how to get the data that had been filter.. on print page, i just call it manually like this : @foreach($profiles as $profile)
        <tr>
            <td class="counterCell"  width="7%"></td>
            <td class="faculty" width="23%">{{$profile->faculty }}</td>
            <td class="program" width="30%"> {{$profile->program }}</td>
            <td class="student_id" width="12%">{{$profile->student_id }}</td>
            <td class="name" width="28%">{{$profile->student_name }}</td>
        </tr>
        @endforeach

how can i get the data after filtering on print page?  the filter table is on report page. (sorry for my bad in english)

**Comment by vsmoraes** [comment]
Sorry but this is not a problem with the PDF component as much as a lack of knowledge of the framework.

Here a some material that may help you:

https://laravel.com/docs/5.2/controllers
https://laravel.com/docs/5.2/views
https://laravel.com/docs/5.2/blade

This issue will be closed.
